### ISSUE TITLE
Server Crash when using Meka Machines

### ISSUE THREAD

**Issue by Myzumi** [Birbs-world/Better-Forge-Chat-Reborn#7]
Heya,

Got a Crash report from using a Mekanism Machine, Specially the Digital miner, after somehow enabling it, it crashed the server once i've joined, After removing bfc, the server was fine without any crashes afterwards.

Crash report is attached, The mod list is basicly atm9 1.0.0 with the bfc, luckperms and discord intregation mod added on the server side.

[crash-2024-12-31_00.44.32-server.txt](https://github.com/user-attachments/files/18278647/crash-2024-12-31_00.44.32-server.txt)

**Comment by Birbs-world** [comment]
interesting, so the digital miners use a fake player, (the fake player is causing the crash)

**Comment by Birbs-world** [comment]
Fixed as per v1.0.4 Birbs-world/pull/8

**Comment by scottbass3** [comment]
@Birbs-world This issue is still happening in 1.21.1. I got it with Mob Grinding Utils which also uses fake players.

Here is the related crash report
[crash-2026-07-17_09.10.57-server.txt](https://github.com/user-attachments/files/30123964/crash-2026-07-17_09.10.57-server.txt)

**Comment by scottbass3** [comment]
I made a pull request to implement the fix into 1.12.1 branch https://github.com/Birbs-world/Better-Forge-Chat-Reborn/pull/28
